# For more info on HTTP files go to https://aka.ms/vs/httpfile

## Getting all issues

GET http://localhost:1338/issues

### Get requests by status

GET http://localhost:1338/issues?status=Open

### Get just a single issue

GET http://localhost:1338/issues/3c5cd70a-4aa8-4302-b922-1a8ebe595661

### Adding a new Issue

POST http://localhost:1338/issues
Content-Type: application/json

{
  "description": "The ship wrecked",
  "application": "The Edmund Fitzgerald",
  "contactEmail": "gordonlightfoot@aol.com"
}